travis:
  secure:
    BINSTAR_TOKEN: ZAk/NwM2jSDIdpNUsHWW1iFSmVW7qvZWmCnlvPStJ20uTjsbNDPKAFupfY8nokB9+dZMHhZGLy2PWf8rhCzQFI11r7weRGktxhRY4gJFyphJxo7Gx3GiiC3AXv9AL4g9I+wXZ7r6QEryqoOH3cF6FiP2FGAAg853FLVHLgrUwc5Cys5qNtctwORLRTxgmi6Z/wtu/DF90tW8IbX3GiRRbN6hqfGZw5e3ei/O+0ZxUPDZh0POMUiIJ4S4FrShRqaguDdiZx6IizQNqWOiL/eAsHFW2bQ6XE9+GlxNoQtbXIR6FpbSA1Fj1r4mdSEC5y6M5DqZOXIiJtODVKFGnF5WHBdUVLrEcEeS0S8Vn0Te0oZLrWXp/DubLXTf/2A+H/jGo94slEAyoC6c/6MxmIGdYm84IK4x3CWiY9Z+jDu5XAmmHWnd1CCNzp59Rwnx2qXtEFUijsoAT+dFZ/BkXH/L+4gd95UEf4p/2QZ/IedVndBwrVEyJHbTylVn6w26ZStcOeAYUAmb1T8Sx22bAQsx+e3XsSZp72Fx9aSS2SSih7aAEii0pQFm0/FQNxkTax8yoBMtdDzLQvPr0l436v5MusBtTrjeJ2kP5kEBBLQtYinqNad5O+Lyk4PSrN0v7PQwB16/+8/qazSi5kjdXjEM/j5l5GloEJRPjQNCtL+Hl3E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
